name: "RELEASE Build"

on:
  push:
    branches:
      - release

jobs:
  build:
    name: "Build Release (JDK17)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          # maven-project-folder: "remsfal-core"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "54059879+calipee@users.noreply.github.com"

          # docker-registry-id: registry.hub.docker.com
          # docker-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # docker-registry-password: ${{ secrets.DOCKER_HUB_PASSWORD }}

          # maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
          # maven-servers: '[{"id": "serverId1", "username": "username", "password": "password", "privateKey": "test", "passphrase": "testes"}, {"id": "serverId2", "username": "username2", "password": "password2"}]'
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: false
          # gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          # gpg-key: ${{ secrets.GPG_KEY }}

          release-branch-name: "release"
