name: "RELEASE Build"

on:
    push: 
#   # Only run this workflow manually from the Actions tab
#   workflow_dispatch:

jobs:
  build:
    name: "Build Release (JDK17)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Extract version from tag
        run: echo "RELEASE_VERSION=${{ steps.branch-names.outputs.current_branch }}" >> $GITHUB_ENV

      - name: Set project version
        run: mvn versions:set -DnewVersion=${RELEASE_VERSION}

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Deploy to Maven Repository
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
